---
- name: 'Clone/Update latest repo'
  git: repo={{ github_repo }}
      dest={{ webapps_dir }}
      accept_hostkey=yes
  become: yes
  become_user: "{{ user }}"

- name: 'create led supervisord confs'
  become: yes
  template: src=led_sub.conf.j2 dest=/etc/supervisor/conf.d/led_sub-{{ item.value.pin }}.conf mode=0644
  with_dict: "{{ leds }}"

- name: 'Restart led_sub via supervisor'
  supervisorctl: name=led_sub-{{ item.value.pin }} state=restarted
  become: yes
  with_dict: "{{ leds }}"
