---

- name: 'Install python and python packages'
  action: apt pkg={{item}} state=installed
  with_items:
    - python
    - python-dev
    - python-pip
    - python-rpi.gpio
    - python-picamera
    - python-yaml
    - libav-tools

- name: 'Install paho-mqtt python package'
  pip: name=paho-mqtt executable=pip state=latest

- name: 'Install wiringpi2 python package'
  pip: name=wiringpi2 executable=pip state=latest

- name: 'Install gpiozero python package'
  pip: name=gpiozero executable=pip state=latest

- name: 'Install boto3 python package'
  pip: name=boto3 executable=pip state=latest

- name: 'Clone latest IoT'
  git: repo=https://github.com/stevewoolley/IoT.git
      dest=/home/pi/IoT
      accept_hostkey=yes
  become: yes
  become_user: pi

- name: 'Install IoT private key'
  copy: src=~/.ssh/credentials/{{ inventory_hostname }}-private.pem dest=/home/pi/IoT/private.pem owner=pi group=pi mode=600

- name: 'Install IoT certificate'
  copy: src=~/.ssh/credentials/{{ inventory_hostname }}-certificate.pem dest=/home/pi/IoT/certificate.pem owner=pi group=pi mode=600

- name: 'Install Root CA'
  copy: src=~/.ssh/credentials/rootCA.pem dest=/home/pi/IoT/rootCA.pem owner=pi group=pi mode=600

- name: 'Configure logrotate'
  template: src=iot_logrotate.j2 dest=/etc/logrotate.d/iot owner=root group=pi mode=0644
  notify:
    - force logrotate

- name: 'Create pi_monitor script'
  template: src=pi_monitor.sh.j2 dest=/home/pi/pi-monitor.sh mode=0755 owner=pi group=pi

- name: 'Crontab entry for pi monitor'
  cron: name="pi monitor" minute="*/5" job="/home/pi/pi-monitor.sh"