---
- name: 'Clone/Update latest repo'
  git:
    repo: https://github.com/stevewoolley/iot.git
    dest: iot
    accept_hostkey: yes
  become: yes
  become_user: "{{ user }}"

- name: 'create supervisor_sub supervisord confs'
  become: yes
  template:
    src: supervisor_sub.conf.j2
    dest: /etc/supervisor/conf.d/supervisor_sub.conf
    mode: 0644
  with_dict: "{{ supervisors }}"

- name: 'Restart supervisor_sub via supervisor'
  supervisorctl:
    name: supervisor_sub
    state: restarted
  become: yes
  with_dict: "{{ supervisors }}"