---
- name: 'Set hostname facts'
  set_fact:
    full_hostname="{{ inventory_hostname }}"
    short_hostname="{{ inventory_hostname.split('.', 1)[0] }}"

- name: 'Install python dependencies'
  pip:
    name: "{{ item }}"
    executable: pip
    state: latest
  with_items:
    - rpi.gpio
    - numpy

- name: 'Clone/Update latest repo'
  git:
    repo: https://github.com/stevewoolley/iot.git
    dest: iot
    accept_hostkey: yes
  become: yes
  become_user: "{{ user }}"

- name: 'create distance_sub supervisord confs'
  become: yes
  template: src=distance_pub.conf.j2 dest=/etc/supervisor/conf.d/distance_sub-{{ item.value.trigger_pin }}-{{ item.value.echo_pin }}.conf mode=0644
  with_dict: "{{ distances }}"

- name: 'Restart distance_sub via supervisor'
  supervisorctl: name=distance_sub-{{ item.value.trigger_pin }}-{{ item.value.echo_pin }} state=restarted
  become: yes
  with_dict: "{{ distances }}"
