---
- name: 'Install required packages'
  action: apt pkg={{item}} state=installed
  with_items:
    - build-essential
    - python-dev
    - python-openssl

- name: 'Clone latest Adafruit DHT'
  git: repo=https://github.com/adafruit/Adafruit_Python_DHT.git
       dest=/usr/src/Adafruit_Python_DHT
       accept_hostkey=yes
  become: yes

- name: 'Install Adafruit DHT'
  command: "{{ item }}"
  args:
    chdir: "/usr/src/Adafruit_Python_DHT"
    creates: "/usr/src/Adafruit_Python_DHT/dist"
  with_items:
    - python setup.py install

- name: 'Set dht monitoring'
  include: dht_monitor.yml

