---

- name: 'Install python packages'
  action: apt pkg={{item}} state=installed
  with_items:
    - python-rpi.gpio
    - python-picamera
    - python-yaml

- name: 'Install AWSIoTPythonSDK python package'
  pip: name=AWSIoTPythonSDK executable=pip state=latest

- name: 'Install paho mqtt python package'
  pip: name=paho-mqtt executable=pip state=present

- name: 'Install wiringpi python package'
  pip: name=wiringpi executable=pip state=latest

- name: 'Install Adafruit DHT python package'
  pip: name=Adafruit_Python_DHT executable=pip state=latest

- name: 'Install gpiozero python package'
  pip: name=gpiozero executable=pip state=latest

- name: 'Install boto3 python package'
  pip: name=boto3 executable=pip state=latest

- name: 'Install psutil python package'
  pip: name=psutil executable=pip state=latest

- name: 'Clone/Update latest repo'
  git: repo={{ github_repo }}
      dest={{ webapps_dir }}
      accept_hostkey=yes
  become: yes
  become_user: "{{ user }}"

- name: 'Install IoT private key'
  copy: src=~/.ssh/credentials/{{ inventory_hostname }}-private.pem dest={{ creds_location }}/private.pem owner={{ user }} group={{ group }} mode=600

- name: 'Install IoT certificate'
  copy: src=~/.ssh/credentials/{{ inventory_hostname }}-certificate.pem dest={{ creds_location }}/certificate.pem owner=pi group=pi mode=600

- name: 'Install Root CA'
  copy: src=~/.ssh/credentials/rootCA.pem dest={{ creds_location }}/rootCA.pem owner={{ user }} group={{ group }} mode=600

- name: 'Configure logrotate'
  template: src=iot_logrotate.j2 dest=/etc/logrotate.d/iot owner={{ user }} group={{ group }} mode=0644
  become: yes
  notify:
    - logrotate-apply

- name: 'Create pi_monitor script'
  template: src=pi_monitor.sh.j2 dest=/root/pi_monitor.sh mode=0755 owner={{ user }} group={{ group }}

- name: 'Crontab entry for pi monitor (fresh)'
  cron: name="pi monitor fresh" minute="*/5" job="/root/pi_monitor.sh fresh"

- name: 'Crontab entry for pi monitor (seldom)'
  cron: name="pi monitor seldom" minute="0" hour="*" job="/root/pi_monitor.sh seldom"
