---
- name: 'Clone/Update latest repo'
  git: repo={{ github_repo }}
      dest={{ webapps_dir }}
      accept_hostkey=yes
  become: yes
  become_user: "{{ user }}"
  notify:
    - restart supervisord

- name: 'create buzzer supervisord confs'
  template: src=buzzer_sub.conf.j2 dest=/etc/supervisor/conf.d/buzzer_sub.conf mode=0644
  sudo: yes
  notify:
    - restart supervisord
