---
- name: 'Clone/Update latest repo'
  git: repo={{ github_repo }}
      dest={{ webapps_dir }}
      accept_hostkey=yes
  become: yes
  become_user: "{{ user }}"

- name: 'create buzzer supervisord confs'
  template: src=buzzer_sub.conf.j2 dest=/etc/supervisor/conf.d/buzzer_sub.conf mode=0644
  become: yes

- name: 'Restart buzzer via supervisor'
  supervisorctl: name=buzzer_sub state=restarted
  become: yes
