---
- name: 'Clone/Update latest repo'
  git: repo={{ github_repo }}
      dest={{ webapps_dir }}
      accept_hostkey=yes
  become: yes
  become_user: "{{ user }}"

- name: 'set supervisor conf'
  become: yes
  template: src=supervisor.conf.j2 dest=/etc/supervisor/supervisord.conf
  notify:
    - restart supervisord

- name: 'create supervisor_sub supervisord confs'
  become: yes
  template: src=supervisor_sub.conf.j2 dest=/etc/supervisor/conf.d/supervisor_sub.conf mode=0644

- name: 'Restart supervisor_sub via supervisor'
  supervisorctl: name=supervisor_sub state=restarted
  become: yes
