---
- name: 'apply raspi-config'
  command: raspi-config --apply-os-config

- name: 'start supervisord'
  service: name=supervisor state=started

- name: 'restart supervisord'
  service: name=supervisor state=restarted

- name: 'Restart rsyslog'
  service: name=rsyslog state=restarted

- name: 'Restart dhcpcd'
  service: name=dhcpcd state=restarted

- name: 'reboot'
  command: shutdown -r now
  async: 0
  poll: 0
  ignore_errors: True
  notify:
    - wait for reboot

- name: 'wait for reboot'
  local_action: wait_for host={{ inventory_hostname }}
                state=started
                timeout=30
  sudo: false