---
- name: 'Restart ssh'
  service: name=ssh state=restarted

- name: 'start supervisord'
  service: name=supervisor state=started

- name: 'restart supervisord'
  service: name=supervisor state=restarted
