---
- name: 'Clone/Update latest repo'
  git:
    repo: https://github.com/stevewoolley/iot.git
    dest: iot
    accept_hostkey: yes
  become: yes
  become_user: "{{ user }}"

- name: 'Supervisor script for pir_pub'
  template:
    src: pir_pub.conf.j2
    dest: "/etc/supervisor/conf.d/pir_pub-{{ item.value.pin }}.conf"
    mode: 0644
  with_dict: "{{ pirs }}"
  become: yes

- name: 'Supervisor script for pirs'
  template:
    src: pirs.conf.j2
    dest: "/etc/supervisor/conf.d/pirs.conf"
    mode: 0644
  become: yes

- name: 'Restart pirs via supervisor'
  supervisorctl:
    name: "pirs:"
    state: restarted
  become: yes
