---
- name: 'Configure WIFI'
  template: src=wpa_supplicant.conf.j2 dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600

- name: 'Disable Wifi Power Management'
  template: src=interfaces.j2 dest=/etc/network/interfaces mode=0644

- name: 'Set Pi Hostname'
  include: hosts.yml

- name: 'generate locale'
  locale_gen: name={{ raspi_config_locale }} state=present

- name: 'set rc.local'
  template: src=rc.local.j2 dest=/etc/rc.local

- name: 'set locale'
  template: src=locale.j2 dest=/etc/default/locale

- name: 'set local timezone'
  timezone: name={{ raspi_config_timezone }}

- name: 'Set additional config vars'
  pi_boot_config:
  args:
    config_vals: "{{raspi_config_other_options}}"
  notify:
    - apply raspi-config

- name: 'change user password'
  user: name={{ user }} update_password=always password={{ pi_user_password }}
