---
- name: 'Configure system'
  include: config.yml
  tags:
    - bootstrap

# Disable ipv6
- sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 1
    sysctl_set: yes

- name: 'Update package cache'
  apt: update_cache=yes

- name: 'Upgrade system to the latest packages'
  apt: upgrade=safe

- name: 'Install common packages'
  action: apt pkg={{item}} state=latest
  with_items:
    - rpi-update
    - git
    - awscli
    - screen
    - supervisor
    - lsb-release
    - build-essential

- name: 'Install python and python libs'
  include: python.yml

# - name: 'Fix rsyslog'
#   include: rsyslog.yml

- name: 'Amazon config setup'
  include: aws.yml
