---
- name: 'Install dependent packages'
  become: yes
  action: apt pkg={{item}} state=installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: 'Install docker from get.docker.com'
  become: yes
  shell: "curl -sSL https://get.docker.com | sh"

- name: 'Adding pi to docker group'
  become: yes
  user: name='{{ user }}'
        groups=docker
        append=yes
